### ISSUE TITLE
Model support request for BAAI/bge-m3

### ISSUE THREAD

**Issue by Leonschmitt** [qdrant/fastembed#210] opened 2024-04-20 23:32 UTC

**Comment by shibingli** [comment] 2024-05-09 08:33
Hope to support BAAI/bge-m3, BAAI/bge-reranker-v2-m3

**Comment by NirantK** [comment] 2024-05-20 08:56
Duplicate of #107 — we're going to look at rerankers in next few weeks though!

**Closed by NirantK** 2024-05-20 08:56 UTC
Labels: model request
