### ISSUE TITLE
facing onnx version issue while installing fastembbed library

### ISSUE THREAD

**Issue by vishalnayak108** [qdrant/fastembed#187] opened 2024-04-04 12:25 UTC
### What happened?

A bug happened!
ERROR: Could not find a version that satisfies the requirement onnxruntime<2.0.0,>=1.17.0 (from fastembed) (from versions: 1.2.0, 1.3.0, 1.4.0, 1.5.1, 1.5.2, 1.6.0, 1.7.0, 1.8.0, 1.8.1, 1.9.0, 1.10.0, 1.11.0, 1.11.1, 1.12.0, 1.12.1, 1.13.1, 1.14.0, 1.14.1, 1.15.0, 1.15.1, 1.16.0, 1.16.1, 1.16.2, 1.16.3)
ERROR: No matching distribution found for onnxruntime<2.0.0,>=1.17.0 (from fastembed)

### Version

0.2.6 (Latest)

### What os are you seeing the problem on?

Linux

### Relevant stack traces and/or logs

```shell
ERROR: Could not find a version that satisfies the requirement onnxruntime<2.0.0,>=1.17.0 (from fastembed) (from versions: 1.2.0, 1.3.0, 1.4.0, 1.5.1, 1.5.2, 1.6.0, 1.7.0, 1.8.0, 1.8.1, 1.9.0, 1.10.0, 1.11.0, 1.11.1, 1.12.0, 1.12.1, 1.13.1, 1.14.0, 1.14.1, 1.15.0, 1.15.1, 1.16.0, 1.16.1, 1.16.2, 1.16.3)
ERROR: No matching distribution found for onnxruntime<2.0.0,>=1.17.0 (from fastembed)
```

**Comment by joein** [comment] 2024-04-04 14:53
@vishalnayak108 I was unable to reproduce the issue
Could you provide more steps to reproduce? E.g. python version, package manager you are using (pip, poetry, etc), OS, etc.

**Comment by PoornshankerPathak** [comment] 2024-04-15 07:56
try installing onnx runtime via "%conda install onnxruntime -c conda-forge"

**Comment by simonwei97** [comment] 2024-04-16 03:13
I have same problem on `MacOS` and Linux().

### MacOS 12.5.1
```bash
❯ pip install fastembed==0.2.6
Collecting fastembed==0.2.6
  Using cached fastembed-0.2.6-py3-none-any.whl.metadata (4.8 kB)
Collecting huggingface-hub<0.21,>=0.20 (from fastembed==0.2.6)
  Using cached huggingface_hub-0.20.3-py3-none-any.whl.metadata (12 kB)
Collecting loguru<0.8.0,>=0.7.2 (from fastembed==0.2.6)
  Using cached loguru-0.7.2-py3-none-any.whl.metadata (23 kB)
Collecting numpy>=1.21 (from fastembed==0.2.6)
  Using cached numpy-1.26.4-cp310-cp310-macosx_10_9_x86_64.whl.metadata (61 kB)
Collecting onnx<2.0.0,>=1.15.0 (from fastembed==0.2.6)
  Using cached onnx-1.16.0-cp310-cp310-macosx_10_15_x86_64.whl.metadata (16 kB)
INFO: pip is looking at multiple versions of fastembed to determine which version is compatible with other requirements. This could take a while.
ERROR: Could not find a version that satisfies the requirement onnxruntime<2.0.0,>=1.17.0 (from fastembed) (from versions: 1.12.0, 1.12.1, 1.13.1, 1.14.1, 1.15.0, 1.15.1, 1.16.0, 1.16.1, 1.16.2, 1.16.3)
ERROR: No matching distribution found for onnxruntime<2.0.0,>=1.17.0

❯ neofetch
                    'c.          xxxxxxx@xxxxxxx
                 ,xNMM.          --------------------------
               .OMMMMo           OS: macOS 12.5.1 21G83 x86_64
               OMMM0,            Host: MacBookPro16,1
     .;loddo:' loolloddol;.      Kernel: 21.6.0
   cKMMMMMMMMMMNWMMMMMMMMMM0:    Uptime: 6 days, 1 hour, 27 mins
 .KMMMMMMMMMMMMMMMMMMMMMMMWd.    Packages: 82 (brew)
 XMMMMMMMMMMMMMMMMMMMMMMMX.      Shell: zsh 5.8.1
;MMMMMMMMMMMMMMMMMMMMMMMM:       Resolution: 1792x1120@2x, 1920x1080@2x
:MMMMMMMMMMMMMMMMMMMMMMMM:       DE: Aqua
.MMMMMMMMMMMMMMMMMMMMMMMMX.      WM: Quartz Compositor
 kMMMMMMMMMMMMMMMMMMMMMMMMWd.    WM Theme: Blue (Light)
 .XMMMMMMMMMMMMMMMMMMMMMMMMMMk   Terminal: tmux
  .XMMMMMMMMMMMMMMMMMMMMMMMMK.   CPU: Intel i7-9750H (12) @ 2.60GHz
    kMMMMMMMMMMMMMMMMMMMMMMd     GPU: Intel UHD Graphics 630, AMD Radeon Pro 5300M
     ;KMMMMMMMWXXWMMMMMMMk.      Memory: 10704MiB / 16384MiB
       .cooc,.    .,coo:.
```

### Linux

```bash
❯ pip install fastembed==0.2.6 -i https://pypi.org/simple                                

Collecting fastembed==0.2.6
  Downloading fastembed-0.2.6-py3-none-any.whl.metadata (4.8 kB)
Collecting huggingface-hub<0.21,>=0.20 (from fastembed==0.2.6)
  Downloading huggingface_hub-0.20.3-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: loguru<0.8.0,>=0.7.2 in /nas/anaconda3/envs/fastembed-py310/lib/python3.10/site-packages (from fastembed==0.2.6) (0.7.2)
Requirement already satisfied: numpy>=1.21 in /nas/anaconda3/envs/fastembed-py310/lib/python3.10/site-packages (from fastembed==0.2.6) (1.26.4)
Requirement already satisfied: onnx<2.0.0,>=1.15.0 in /nas/anaconda3/envs/fastembed-py310/lib/python3.10/site-packages (from fastembed==0.2.6) (1.16.0)
INFO: pip is looking at multiple versions of fastembed to determine which version is compatible with other requirements. This could take a while.
ERROR: Could not find a version that satisfies the requirement onnxruntime<2.0.0,>=1.17.0 (from fastembed) (from versions: 1.12.0, 1.12.1, 1.13.1, 1.14.0, 1.14.1, 1.15.0, 1.15.1, 1.16.0, 1.16.1, 1.16.2, 1.16.3)
ERROR: No matching distribution found for onnxruntime<2.0.0,>=1.17.0

❯ cat /etc/os-release  
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```

**Comment by Anush008** [comment] 2024-04-18 05:47
Can you try ```pip install --upgrade pip``` followed by ```pip install onnxruntime==1.17.1```?

**Comment by NirantK** [comment] 2024-04-18 15:23
ONNXRuntime definitely has these versions on PyPi: https://pypi.org/project/onnxruntime/
Could be a package manager issue e.g. pip version or conda perhaps?

**Comment by simonwei97** [comment] 2024-04-22 01:27
> Can you try `pip install --upgrade pip` followed by `pip install onnxruntime==1.17.1`?

```bash
❯ pip install --upgrade pip && pip install onnxruntime==1.17.1 -i https://pypi.org/simple
Requirement already satisfied: pip in /Users/xxx/miniconda3/envs/fastembed-py310/lib/python3.10/site-packages (24.0)
ERROR: Could not find a version that satisfies the requirement onnxruntime==1.17.1 (from versions: 1.12.0, 1.12.1, 1.13.1, 1.14.1, 1.15.0, 1.15.1, 1.16.0, 1.16.1, 1.16.2, 1.16.3)
ERROR: No matching distribution found for onnxruntime==1.17.1
```


```bash
❯ pip install --upgrade pip && pip install onnxruntime==1.17.1 -i https://pypi.org/project/onnxruntime/
Requirement already satisfied: pip in /Users/xxx/miniconda3/envs/fastembed-py310/lib/python3.10/site-packages (24.0)
Looking in indexes: https://pypi.org/project/onnxruntime/
ERROR: Could not find a version that satisfies the requirement onnxruntime==1.17.1 (from versions: none)
ERROR: No matching distribution found for onnxruntime==1.17.1
```

**Comment by NirantK** [comment] 2024-04-22 11:41
@simonwei97 looks like ONNXRuntime is no longer going to support CentOS 7 and recommends using Ubuntu instead.

https://github.com/microsoft/onnxruntime/issues/20055

I'm afraid there is not much we can do about this. That said, you can always clone FastEmbed locally, and try if an older of onnxruntime works with a [previous release](https://github.com/qdrant/fastembed/releases)

I am closing this issue for now — please open a new issue if there's something we can do to help!

**Closed by NirantK** 2024-04-22 11:41 UTC
Labels: dependencies

**Comment by simonwei97** [comment] 2024-04-22 13:18
> @simonwei97 looks like ONNXRuntime is no longer going to support CentOS 7 and recommends using Ubuntu instead.
> 
> [microsoft/onnxruntime#20055](https://github.com/microsoft/onnxruntime/issues/20055)
> 
> I'm afraid there is not much we can do about this. That said, you can always clone FastEmbed locally, and try if an older of onnxruntime works with a [previous release](https://github.com/qdrant/fastembed/releases)
> 
> I am closing this issue for now — please open a new issue if there's something we can do to help!

OK. I got it.

MacOS x86(`macOS 12.5.1 x86_64`) has same issue. 

While MacOS arm (`macOS 14.1 arm64`) add `onnxruntime==1.17.3` and `fastembedd==0.2.6` successfully.
