### ISSUE TITLE
Add support for Image/Multimodal Model

### ISSUE THREAD

**Issue by atarora** [qdrant/fastembed#92] opened 2024-01-16 09:09 UTC
Considering Qdrant would support "any" kind of embedding, we should have a way to process image/multimodal embeddings.

Is there an existing way to do it through Fastembed?

**Comment by NirantK** [comment] 2024-01-17 10:38
Can consider adding CLIP support #70

**Comment by NirantK** [comment] 2024-01-17 10:39
Is there anything other than images or non-CLIP models which we're interested in?

**Comment by NirantK** [comment] 2024-03-13 12:59
Closing this as duplicate of #70 for now

**Closed by NirantK** 2024-03-13 12:59 UTC
Labels: model request
